from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from app.schemas.base import BaseSchema


class AgentRecommendation(BaseModel):
    """
    Represents the core recommendation output produced by the agent.
    """

    #: Suggested short alias for the analyzed entity (if applicable)
    suggested_alias: Optional[str]

    #: Classification tags generated by the agent
    tags: List[str] = []

    #: Risk score between 0.0 (safe) and 1.0 (high risk)
    risk_score: float = Field(..., ge=0.0, le=1.0)

    #: Optional free-form notes or explanation
    notes: Optional[str]


class AgentResponse(BaseSchema):
    """
    Standard API response returned by the agent service.
    """

    #: Indicates whether the agent completed successfully
    success: bool

    #: Agent-generated recommendations
    recommendations: AgentRecommendation

    #: Additional metadata for debugging or reasoning purposes
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Extra debug or reasoning info"
    )
